// Generated by CoffeeScript 1.3.1
(function() {
  var c, http, i, options, query, s, send;

  http = require('http');

  options = {
    host: '10.144.3.211',
    port: 80,
    path: '/'
  };

  s = 0;

  c = 0;

  query = function(param) {
    options.path = "/?" + i;
    s++;
    return http.get(options, function(res) {
      var pageData;
      pageData = "";
      res.setEncoding('utf8');
      res.on('data', function(chunk) {
        return pageData += chunk;
      });
      res.on('end', function() {
        return console.log(pageData);
      });
      console.log(param);
      c++;
      return send();
    });
  };

  i = 0;

  send = function() {
    while (false) {
      if (s - c > 10000) {
        break;
      }
      query(i++);
    }
    return query(i++);
  };

  send();

}).call(this);
